[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Blake3Hash = "8f478455-a32d-4928-b0e4-72b19a7d5574"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
HPCSparseArrays = "5bdd2be4-ae34-42ef-8b36-f4c85d48f377"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MUMPS = "55d2b088-9f4e-11e9-26c0-150b02ea6a46"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SafePETSc = "50acdc01-ce88-4ca7-bd87-6916c254362e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[sources.HPCSparseArrays]
path = ".."

[sources.SafePETSc]
path = "../../SafePETSc.jl"
