[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
HPCSparseArrays = "537374f1-5608-4525-82fb-641dce542540"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
Adapt = "4"
Documenter = "1"
KernelAbstractions = "0.9"
